name: Build iOSFakeRun Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build -c Release -o iOSFakeRun-Windows
      - name: Get DeveloperDiskImage
        run: cd iOSFakeRun-Windows && git clone https://github.com/pdso/DeveloperDiskImage.git --depth=1
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: iOSFakeRun-Windows
          path: iOSFakeRun-Windows
